# Generated by Django 2.1.7 on 2020-08-17 18:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200817_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 8, 17, 15, 11, 52, 515956)),
        ),
    ]
